issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-forks/minio:ref:refs/heads/master
claim_pattern:
  workflow_ref: chainguard-forks/minio/.github/workflows/release.yml@refs/heads/master

permissions:
  contents: write
